spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ditto
        username: postgres
        password: postgres

    jpa:
        hibernate:
            database-platform: org.hibernate.dialect.PostgreSQL94Dialect
            format_sql: true
            ddl-auto: update

    cloud:
        openfeign:
            client:
                config:
                    default:
                        connectTimeout: 5000
                        readTimeout: 5000
                        loggerLevel: full
                    github:
                        url: https://api.github.com
                        requestInterceptors:
                            - com.gngsn.ditto.adapter.output.interceptor.GithubRequestHeaderInterceptor
#                        errorDecoder: com.example.SimpleErrorDecoder
#                        retryer: com.example.SimpleRetryer
#                        defaultQueryParameters:m
#                            query: queryValue
#                        defaultRequestHeaders:
#                            header: headerValue
#                        responseInterceptor: com.example.BazResponseInterceptor
#                        dismiss404: false
#                        encoder: com.example.SimpleEncoder
#                        decoder: com.example.SimpleDecoder
#                        contract: com.example.SimpleContract
#                        capabilities:
#                            - com.example.FooCapability
#                            - com.example.BarCapability
#                        queryMapEncoder: com.example.SimpleQueryMapEncoder
#                        micrometer.enabled: false
